import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { config, ROOT } from '../src/config.js';
import { closeDb, execute } from '../src/db.js';
import { Engine } from '../src/pipeline.js';
import { validate, ValidationError } from '../src/sql.js';

const QUESTIONS = [
  ['Simple lookup', 'How many customers are there?'],
  ['Filter on text, no limit asked for', 'List all employees whose title contains sales'],
  ['Fan-out trap', 'What is the total revenue from each customer in Brazil?'],
  ['Ambiguous - readings disagree, so it asks', 'Who is our best customer?'],
  ['Ambiguous - answered with a declared proxy', 'Which tracks are the most popular?'],
  ['Unanswerable - no cost data', 'What is the profit margin on each album?'],
  ['Unanswerable - no usage events', 'How many tracks were streamed last month?']
];

const ATTACKS = [
  'SELECT * FROM Customer; DROP TABLE Customer',
  'DELETE FROM Invoice',
  'PRAGMA writable_schema = 1',
  'SELECT t.PlayCount FROM Track t',
  "SELECT load_extension('/tmp/x.so')"
];

const engine = new Engine();
const out = ['# Demo', '', `Generated by \`npm run demo\` using **${engine.client.name}/${engine.client.model}**.`, '', '---', ''];

for (const [label, question] of QUESTIONS) {
  const result = await engine.ask(question);
  out.push(`## ${label}`, '', `**Q: ${question}**`, '', `\`${result.outcome}\``, '', result.answer, '');

  if (result.assumption) out.push(`> assumption: ${result.assumption}`, '');
  for (const option of result.options) out.push(`- **${option.label}** -> \`${option.wouldAnswer}\``);
  if (result.options.length) out.push('');

  if (result.evidence) {
    out.push('```sql', result.evidence.sql, '```', '');
    out.push(`| ${result.evidence.columns.join(' | ')} |`, `|${'---|'.repeat(result.evidence.columns.length)}`);
    for (const row of result.evidence.rows.slice(0, 8)) {
      out.push(`| ${row.map((cell) => (cell === null ? 'NULL' : String(cell))).join(' | ')} |`);
    }
    out.push('', `_${result.evidence.rowCount} rows · ${result.evidence.durationMs} ms_`, '');
  }

  out.push(`_verification: ${result.verification}_`, '', '---', '');
}

out.push('## Guardrails', '', 'Hostile SQL sent straight to the validator:', '', '| input | result |', '|---|---|');

for (const sql of ATTACKS) {
  let verdict;
  try {
    validate(sql, engine.catalog, config.maxRows);
    verdict = '**ACCEPTED - THIS IS A BUG**';
  } catch (error) {
    if (!(error instanceof ValidationError)) throw error;
    verdict = `rejected: ${error.message}`;
  }
  out.push(`| \`${sql}\` | ${verdict.slice(0, 120)} |`);
}

out.push('', 'And with the validator skipped entirely, the database still refuses:', '');
for (const sql of ['DELETE FROM Invoice', 'DROP TABLE Customer']) {
  try {
    execute(sql);
    out.push(`- \`${sql}\` -> EXECUTED, THIS IS A BUG`);
  } catch (error) {
    out.push(`- \`${sql}\` -> blocked: ${error.message}`);
  }
}

const target = join(ROOT, 'docs', 'DEMO.md');
mkdirSync(join(ROOT, 'docs'), { recursive: true });
writeFileSync(target, `${out.join('\n')}\n`);
process.stdout.write(`wrote ${target}\n`);

closeDb();
